openapi: 3.1.0
info:
  title: AutoMFG Order Management API
  version: 1.0.0
  description: Order Management Context — dealer order placement and change operations

servers:
  - url: http://localhost:8080
    description: Local development

paths:
  /api/v1/orders:
    post:
      operationId: placeOrder
      summary: Place a new vehicle order (UC-01)
      description: |
        Validates option compatibility (BR-02), enforces 50-order limit (BR-01),
        calculates delivery date (BR-03) and price quote, then publishes OrderPlacedEvent.
      tags: [Orders]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PlaceOrderRequest'
      responses:
        '201':
          description: Order created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '400':
          description: Validation error (incompatible options, missing fields)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Business rule violation (50-order limit exceeded)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    get:
      operationId: listOrders
      summary: List orders with optional filters
      tags: [Orders]
      parameters:
        - name: dealerId
          in: query
          schema:
            type: string
        - name: status
          in: query
          schema:
            type: string
            enum: [PLACED, SCHEDULED, IN_PRODUCTION, COMPLETED, CANCELLED]
      responses:
        '200':
          description: List of orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OrderSummaryResponse'

  /api/v1/orders/{orderId}:
    get:
      operationId: getOrder
      summary: Get order details
      tags: [Orders]
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Order details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '404':
          description: Order not found

  /api/v1/orders/{orderId}/changes:
    post:
      operationId: changeOrder
      summary: Change an existing order (UC-05)
      description: |
        Changes color or option packages on orders not yet in production (BR-13).
        Enforces max 3 changes (BR-15). Model changes result in cancel + new order (BR-14).
      tags: [Orders]
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangeOrderRequest'
      responses:
        '200':
          description: Order changed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '409':
          description: Change not allowed (production started, max changes reached)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    PlaceOrderRequest:
      type: object
      required: [dealerId, vehicleModelCode, colorCode]
      properties:
        dealerId:
          type: string
          example: "DEALER-001"
        vehicleModelCode:
          type: string
          example: "MODEL-X-SEDAN"
        colorCode:
          type: string
          example: "SILVER"
        optionPackageCodes:
          type: array
          items:
            type: string
          example: ["LUXURY-INTERIOR", "PREMIUM-AUDIO"]

    ChangeOrderRequest:
      type: object
      properties:
        newColorCode:
          type: string
          nullable: true
        newOptionPackageCodes:
          type: array
          items:
            type: string
          nullable: true
        newVehicleModelCode:
          type: string
          nullable: true
          description: If provided, original order is cancelled and a new one is created

    OrderResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        orderNumber:
          type: string
          example: "ORD-202602-00001"
        dealerId:
          type: string
        vehicleModelCode:
          type: string
        colorCode:
          type: string
        optionPackageCodes:
          type: array
          items:
            type: string
        status:
          type: string
          enum: [PLACED, SCHEDULED, IN_PRODUCTION, COMPLETED, CANCELLED]
        estimatedDeliveryDate:
          type: string
          format: date
        priceQuote:
          type: number
          format: decimal
        changeCount:
          type: integer
        createdAt:
          type: string
          format: date-time

    OrderSummaryResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
        orderNumber:
          type: string
        dealerId:
          type: string
        vehicleModelCode:
          type: string
        status:
          type: string
        estimatedDeliveryDate:
          type: string
          format: date

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
        details:
          type: array
          items:
            type: string
